# Site settings
name: "Seis*"
title: A getting started page for regional-, global-, and exploration-scale seismic inversion
description: >
  A getting started page for regional-, global-, and exploration-scale seismic inversion
  baseurl: "" 
url: "http://seisstar.github.io/SeisStar/"

# Build settings
markdown: kramdown
highlighter: rouge 
baseurl: /SeisStar

kramdown:
  input: GFM

collections:
  docs:
    output: true

gems:
- rouge
