# Site settings
name: "Seis*"
title: A seismic adjoint tomography ecosystem 
description: >
  A seismic adjoint tomography ecosystem 
  baseurl: "" 
url: "http://seisstar.github.io/SeisStar/"

# Build settings
markdown: kramdown
baseurl: /SeisStar

kramdown:
  input: GFM

collections:
  docs:
    output: true
